---
- name: Start NGINX
  service: name=nginx state=started enabled=true
- name: Supprimer default.conf  de NGINX
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: nginx reload
...
