---
- hosts: squid
  remote_user: root
  vars_files:
    - /etc/ansible/secret.yml
  become: yes
  tasks:
  - name: login to docker registry
    docker_login:
      username: "{{ docker_hub_username }}"
      password: "{{ docker_hub_password }}"
      email: "{{ docker_hub_email }}"
  - name: create custom docker container
    docker_container:
      name: mycustomcontainer
      image: 7ephiroth/myapacheweb:v1
      state: absent
      ports:
        "82:80"
