---
- name: Playbook installation Nginx sur Debian 8
  hosts: debian8
  remote_user: root
  vars:
    user : toto
    domains:
      - domain: flaccoelite.fr
        php: yes
      - domain: enzoelite.fr
        php: no
        repo: https://github.com/Grafikart/grafikart.github.io.git
  roles:
    - toolsdeb8
    - userdeb8
    - debian8nginx
#    - php7
...
