---
- name: creation user
  user: name={{ user }} comment="master" shell=/bin/bash
- name: utilisation de clef
  authorized_key: user={{ user }} key={{ lookup('file', '/home/{{ user }}/.ssh/id_rsa.pub') }}
- name: utilisation de template pour sudoers tron
  template: src=templates/sudoers.j2 dest=/etc/sudoers.d/{{ user }} validate='/usr/sbin/visudo -cf %s'
...
