---
  - name: creation configuration squid backup et redemarrage de squid
    template:
      src: templates/squid.j2
      dest: /etc/squid3/squid.conf
      owner: root
      group: root
      mode: 0644
      backup: yes
    notify: restart squid
...
